### ISSUE TITLE
Add local setup instructions to README

### ISSUE THREAD

**Issue by exogen** [evancz/ui-perf#5]
I couldn't figure out how to actually run this (locally, so I could make changes).

When I open `index.html`, I just get `ReferenceError: Elm is not defined`. That was after installing Elm and doing `elm-package install` in `src` which was just a guess on my part. That didn't seem to fix anything.

Instructions for setting this up would be nice!

**Comment by evancz** [comment]
I'd switch to the gh-pages branch. That has all the assets set up already. From there you can recompile things however you want. I'll add a note about this though!

**Comment by evancz** [comment]
Note added!
